USE ASSET_MANAGEMENT
GO

SELECT * FROM USUARIO;

DROP PROCEDURE IF EXISTS VALIDAR_USUARIO
GO

CREATE PROCEDURE VALIDAR_USUARIO
    @IN_EMAIL       VARCHAR(70),
    @IN_CONTRASENNA VARCHAR(25)
AS
BEGIN

    SELECT 
        U.ID_USUARIO, -- Include the 'idUsuario' column in the selection
        U.NOMBRE,
        U.CORREO,
        U.ID_ROLE,
		U.CONTRASENNA,
		U.ESTADO,
		U.ESTADO_CONTRASENNA
    FROM USUARIO U
    WHERE U.CORREO = @IN_EMAIL AND U.CONTRASENNA = @IN_CONTRASENNA

END


EXEC VALIDAR_USUARIO 'cmorale@asset_management.com','Cris123@'
GO

CREATE OR ALTER VIEW RESUMEN_USUARIOS AS
	SELECT 
		U.ID_USUARIO,
		U.NOMBRE,
		U.CORREO,
		U.CONTRASENNA,
		U.ID_ROLE,
		U.ESTADO,
		UR.NOMBRE_ROLE
	FROM USUARIO U
	INNER JOIN USUARIO_ROLE UR ON UR.ID_ROLE = U.ID_ROLE;
GO

SELECT * FROM RESUMEN_USUARIOS;
GO

CREATE OR ALTER PROCEDURE DESACTIVAR_USUARIO
	@ID_USUARIO	INT
AS
BEGIN

	UPDATE USUARIO SET ESTADO = 0 WHERE ID_USUARIO = @ID_USUARIO

END
GO

CREATE OR ALTER PROCEDURE ACTIVAR_USUARIO
	@ID_USUARIO INT
AS
BEGIN

	UPDATE USUARIO SET ESTADO = 1 WHERE ID_USUARIO = @ID_USUARIO

END
GO

EXEC ACTIVAR_USUARIO 1

SELECT * FROM USUARIO

Use ASSET_MANAGEMENT;

INSERT INTO USUARIO (NOMBRE,CORREO,CONTRASENNA,ID_ROLE) VALUES
	('Santiago Marin','smarin@assetmanagement.com','Cris123@',1);
