CREATE DATABASE ASSET_MANAGEMENT_DW
GO

USE ASSET_MANAGEMENT_DW
GO


-- Create DIM_CLASE
SELECT 
	ID_CLASE,
	DESCRIPCION_CLASE
FROM ASSET_MANAGEMENT.DBO.CLASE; 
GO

CREATE TABLE DIM_CLASE(
	ID_CLASE INT NOT NULL CONSTRAINT PK_CLASE PRIMARY KEY, 
	DESCRIPCION_CLASE VARCHAR(255)
)
GO

INSERT INTO DIM_CLASE
	SELECT
		ID_CLASE,
		DESCRIPCION_CLASE
	FROM ASSET_MANAGEMENT.DBO.CLASE
GO

SELECT * FROM DIM_CLASE; 

-- Create DIM_UBICACION
CREATE TABLE DIM_UBICACION(
	ID_UBICACION		INT CONSTRAINT PK_UBICACION PRIMARY KEY,
	ID_EDIFICIO			VARCHAR(20) NOT NULL,
	DESCRIPCION_SECCION	VARCHAR(50) NOT NULL,
); 
GO

INSERT INTO DIM_UBICACION
	SELECT
		*
	FROM ASSET_MANAGEMENT.DBO.UBICACION;
GO

-- Create DIM_DUENNO
CREATE TABLE DIM_DUENNO(
	ID_DUENNO		INT NOT NULL CONSTRAINT PK_DUENNO PRIMARY KEY, 
	NOMBRE			VARCHAR(255), 
	CORREO			VARCHAR(255)
)
GO

INSERT INTO DIM_DUENNO
	SELECT 
		ID_USUARIO,
		NOMBRE,
		CORREO
	FROM 
		ASSET_MANAGEMENT.DBO.USUARIO;
GO

SELECT * FROM DIM_DUENNO


-- Create DIM_ESTADO
CREATE TABLE DIM_ESTADO (
	ID_ESTADO			INT CONSTRAINT PK_ESTADO PRIMARY KEY, 
	DESCRIPCION_ESTADO	VARCHAR(50) NOT NULL
)
GO

INSERT INTO DIM_ESTADO
	SELECT * FROM ASSET_MANAGEMENT.DBO.ESTADO;
GO

SELECT * FROM DIM_ESTADO; 

-- Create DIM_FECHA
CREATE TABLE DIM_FECHA(
   FEC_ID                INTEGER NOT NULL CONSTRAINT PK_FECH_ID PRIMARY KEY, /* Format: AAAAMMDD */
   FEC_FECHA             datetime NOT NULL,        /* Actual date */
   FEC_DIA_SEMANA        tinyint NULL,             /* 1 to 7 */
   FEC_DIA_MES           tinyint NULL,             /* 1 to 31 */
   FEC_DIA_PERIODO       smallint NULL,            /* 1 to 366 */
   FEC_SEMANA            tinyint NULL,             /* 1 to 53 */
   FEC_MES               tinyint NULL,             /* 1 to 12 */
   FEC_TRIMESTRE         tinyint NULL,             /* 1 to 4 */
   FEC_SEMESTRE          tinyint NULL,             /* 1 to 2 */
   FEC_PERIODO           char(4) NULL,             /* Just the number */
   FEC_SEMANA_PERIODO    nvarchar(25) NULL,        /* Week Unique Identifier: Week + Year */
   FEC_MES_PERIODO       nvarchar(25) NULL,        /* Month Unique Identifier: Month + Year */
   FEC_TRIMESTRE_PERIODO nvarchar(25) NULL,        /* Quarter Unique Identifier: Quarter + Year */
   FEC_SEMESTRE_PERIODO  nvarchar(25) NULL,        /* Semester Unique Identifier: Semester + Year */
   FEC_DIA_SEMANA_ENG    nvarchar(10) NULL,
   FEC_DIA_SEMANA_ESP    nvarchar(10) NULL,
   FEC_NOMBRE_MES_ING    nvarchar(10) NULL,        /* January to December */
   FEC_NOMBRE_MES_ESP    nvarchar(10) NULL,        /* Enero a Diciembre */
)
GO

SELECT * FROM DIM_FECHA

DROP TABLE FAC_ACTIVO; 

-- Insert for FAC table
CREATE TABLE FAC_ACTIVO(
	ID_ACTIVO				INT NOT NULL CONSTRAINT PK_ACTIVO PRIMARY KEY, 
	ID_CLASE				INT NOT NULL, 
	ID_UBICACION			INT NOT NULL, 
	ID_DUENNO				INT NOT NULL, 
	ID_ESTADO				INT NOT NULL, 
	DESCRIPCION_ACTIVO		VARCHAR(255) NULL,
	VALOR_ADQUISICION		FLOAT NOT NULL, 
	FECHA_ADQUISICION		INT NOT NULL, 
	PERIODOS_DEPRECIADOS	INT NOT NULL,
	VIDA_UTIL				INT NOT NULL
	CONSTRAINT FK_ID_CLASE FOREIGN KEY (ID_CLASE) REFERENCES DIM_CLASE(ID_CLASE),
	CONSTRAINT FK_ID_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES DIM_UBICACION(ID_UBICACION),
	CONSTRAINT FK_ID_DUENNO FOREIGN KEY (ID_DUENNO) REFERENCES DIM_DUENNO(ID_DUENNO), 
	CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES DIM_ESTADO(ID_ESTADO),
	CONSTRAINT FK_FECHA_ADQUISICION FOREIGN KEY (FECHA_ADQUISICION) REFERENCES DIM_FECHA(FEC_ID)
)
GO

INSERT INTO FAC_ACTIVO
	SELECT 
		A.ID_ACTIVO,
		A.ID_CLASE,
		A.ID_UBICACION,
		A.ID_DUENNO,
		A.ID_ESTADO,
		A.DESCRIPCION_ACTIVO,
		A.VALOR_ADQUISICION,
		CONVERT(INT,CONVERT(VARCHAR,A.FECHA_ADQUISICION,112)) AS FECHA_ADQUISICION,
		A.PERIODOS_DEPRECIADOS,
		C.VIDA_UTIL
	FROM ASSET_MANAGEMENT.DBO.ACTIVO A
	INNER JOIN ASSET_MANAGEMENT.DBO.CLASE C ON A.ID_CLASE = C.ID_CLASE
	INNER JOIN ASSET_MANAGEMENT.DBO.UBICACION U ON A.ID_UBICACION = U.ID_UBICACION
	INNER JOIN ASSET_MANAGEMENT.DBO.ESTADO E ON A.ID_ESTADO = E.ID_ESTADO
GO

