USE ASSET_MANAGEMENT
GO

----------------- Función para resumir la información de los asientos 
--- Vista que resume la información basica del asiento 
CREATE OR ALTER VIEW RESUMEN_ASIENTOS 
AS
	SELECT 
		A.ID_ASIENTO,
		A.FECHA,
		A.DESCRIPCION,

		-- Deine al clase del activo
		CASE WHEN A.ID_CLASE IS NOT NULL THEN
			(SELECT C.DESCRIPCION_CLASE FROM CLASE C WHERE C.ID_CLASE = A.ID_CLASE)
		ELSE
			(SELECT 'No relacionado a activos')
		END AS DESCRIPCION_CLASE,

		-- Se optiene el monto del total del journal
		(SELECT SUM(AL.DEBITO) FROM ASIENTO_LINEA AL WHERE AL.ID_ASIENTO = A.ID_ASIENTO) AS TOTAL_ASIENTO
	FROM ASIENTO A
GO

----------------- Función para resumir la ecuación contable. 
--- Vista para calcular la ecuación contable utilizando la información de asiento
CREATE OR ALTER VIEW ECUACION_CONTABLE
AS	
	SELECT
		CAT.DESCRIPCION_CATEGORIA AS CATEGORIA, 
		SUM(
			CASE WHEN (CC.NATURALEZA = 'D') THEN
				AL.DEBITO - AL.CREDITO
			ELSE
				AL.CREDITO - AL.DEBITO
			END
		) AS TOTAL_BALANCE
	FROM ASIENTO_LINEA AL
	INNER JOIN CUENTA_CONTABLE CC ON CC.ID_CUENTA = AL.ID_CUENTA_CONTABLE
	INNER JOIN CATEGORIA_CUENTA CAT ON CAT.ID_CATEGORIA = CC.ID_CATEGORIA
	GROUP BY CAT.DESCRIPCION_CATEGORIA
GO

SELECT * FROM ECUACION_CONTABLE;
GO

-- Vist de la información de las lineas de todos los asientos
CREATE OR ALTER VIEW RESUMEN_ASIENTO_LINEAS 
AS
	SELECT
		AL.ID_ASIENTO_LINEA,
		AL.ID_CUENTA_CONTABLE,
		AL.DESCRIPCION_LINEA,
		AL.DEBITO,
		AL.CREDITO,
		AL.DEBITO - AL.CREDITO AS BALANCE
	FROM ASIENTO_LINEA AL
GO

SELECT * FROM RESUMEN_ASIENTO_LINEAS
GO

-- Procedimiento para el body de un solo asiento
CREATE OR ALTER PROCEDURE RESUMEN_ASIENTO_LINEAS_BODY
	@IN_ASIENTO_ID	INT
AS
BEGIN
	SELECT
		AL.ID_ASIENTO_LINEA,
		AL.ID_CUENTA_CONTABLE,
		AL.DESCRIPCION_LINEA,
		AL.DEBITO,
		AL.CREDITO,
		AL.DEBITO - AL.CREDITO AS BALANCE
	FROM ASIENTO_LINEA AL
	WHERE AL.ID_ASIENTO = @IN_ASIENTO_ID

END; 

EXEC RESUMEN_ASIENTO_LINEAS_BODY 2
GO

