CREATE OR ALTER VIEW CLASSES_LIST
AS
	SELECT
		C.ID_CLASE,
		C.DESCRIPCION_CLASE,
		(SELECT CC.ID_CUENTA FROM CLASE_CUENTA CC WHERE CC.ID_CLASE = C.ID_CLASE AND ID_CATEGORIA_CUENTA = 1) AS CUENTA_ACTIVO,
		(SELECT CC.ID_CUENTA FROM CLASE_CUENTA CC WHERE CC.ID_CLASE = C.ID_CLASE AND ID_CATEGORIA_CUENTA = 5) AS CUENTA_GASTO,
		(SELECT CC.ID_CUENTA FROM CLASE_CUENTA CC WHERE CC.ID_CLASE = C.ID_CLASE AND ID_CATEGORIA_CUENTA = 6) AS CUENTA_DEP_ACUMULADA,
		C.VIDA_UTIL
	FROM CLASE C
GO


SELECT * FROM CLASSES_LIST

SELECT * FROM CLASE
SELECT * FROM CLASE_CUENTA
GO;

CREATE OR ALTER PROCEDURE CREAR_CLASE
	@IN_CLASS_DESCRIPTION    VARCHAR(50),
    @IN_ASSET_ACCOUNT        VARCHAR(15),
    @IN_DEP_ACUM_ACCOUNT     VARCHAR(15),
    @IN_EXPENSE_ACCOUNT      VARCHAR(15),
    @IN_USEFULL_LIFE         INT
AS
	DECLARE
		@VAR_NUEVA_CLASE_ID		INT;
BEGIN

	INSERT INTO CLASE (DESCRIPCION_CLASE,VIDA_UTIL) VALUES (@IN_CLASS_DESCRIPTION,@IN_USEFULL_LIFE);
	SET @VAR_NUEVA_CLASE_ID = @@IDENTITY;

	INSERT INTO CLASE_CUENTA (ID_CLASE,ID_CUENTA,ID_CATEGORIA_CUENTA) VALUES
		(@VAR_NUEVA_CLASE_ID,@IN_ASSET_ACCOUNT,1),
		(@VAR_NUEVA_CLASE_ID,@IN_EXPENSE_ACCOUNT,5),
		(@VAR_NUEVA_CLASE_ID,@IN_DEP_ACUM_ACCOUNT,6);

	INSERT INTO TIPO_VALIDACION (ID_CLASE,DESCRIPCION_VALIDACION) VALUES
		(@VAR_NUEVA_CLASE_ID,'Placa')

END;
GO

SELECT * FROM TIPO_VALIDACION; 

SELECT * FROM CLASE
SELECT * FROM CLASE_CUENTA WHERE ID_CLASE = 5
SELECT * FROM CUENTA_CONTABLE
GO

CREATE OR ALTER VIEW RESUMEN_ACTIVOS_CLASE
AS
	SELECT 
		 C.DESCRIPCION_CLASE,
		 (SELECT COUNT(*) FROM ACTIVO A WHERE A.ID_CLASE = C.ID_CLASE) AS TOTAL_ACTIVOS
	FROM CLASE C;
GO 

SELECT * FROM RESUMEN_ACTIVOS_CLASE;
GO 

CREATE OR ALTER PROCEDURE MODIFICAR_CLASE
	@IN_ID_ACTIVO		INT, 
	@IN_ID_NUEVA_CLASE	INT
AS
	DECLARE
		@VAR_CLASE_ACTUAL_ID			INT,
		@VAR_CUENTA_DEPRECIACION		VARCHAR(15),
		@VAR_CUENTA_GASTO				VARCHAR(15),
		@VAR_CUENTA_ACTIVO				VARCHAR(15),

		@VAR_CUENTA_DEPRECIACION_NEW	VARCHAR(15),
		@VAR_CUENTA_GASTO_NEW			VARCHAR(15),
		@VAR_CUENTA_ACTIVO_NEW			VARCHAR(15),

		@VAR_MONTO_RECONOCIMIENTO		FLOAT, 
		@VAR_MONTO_DEPRECIACION			FLOAT,

		@VAR_ID_ASIENTO					INT,
		@VAR_JE_DESCRIPTION				VARCHAR(255)
BEGIN
	
	--Recuperar la información actual del activo
	SELECT @VAR_CLASE_ACTUAL_ID = ID_CLASE FROM ACTIVO WHERE ID_ACTIVO = @IN_ID_ACTIVO; 
	SELECT @VAR_CUENTA_DEPRECIACION = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID AND ID_CATEGORIA_CUENTA = 6; 
	SELECT @VAR_CUENTA_GASTO = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID AND ID_CATEGORIA_CUENTA = 5; 
	SELECT @VAR_CUENTA_ACTIVO = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID AND ID_CATEGORIA_CUENTA = 1; 
	SELECT @VAR_MONTO_RECONOCIMIENTO = VALOR_ADQUISICION FROM ACTIVO WHERE ID_ACTIVO = @IN_ID_ACTIVO; 
	SELECT @VAR_MONTO_DEPRECIACION = DEPRECIACION_ACUMULADA FROM AUXILIAR_DEPRECIACION WHERE ID_ACTIVO = @IN_ID_ACTIVO; 

	-- Recuperar la información actual del activo
	SELECT @VAR_CUENTA_DEPRECIACION_NEW = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @IN_ID_NUEVA_CLASE AND ID_CATEGORIA_CUENTA = 6; 
	SELECT @VAR_CUENTA_GASTO_NEW = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @IN_ID_NUEVA_CLASE AND ID_CATEGORIA_CUENTA = 5; 
	SELECT @VAR_CUENTA_ACTIVO_NEW = ID_CUENTA FROM CLASE_CUENTA WHERE ID_CLASE = @IN_ID_NUEVA_CLASE AND ID_CATEGORIA_CUENTA = 1; 


	SELECT @VAR_JE_DESCRIPTION = CONCAT('Cambio clase activo - ',DESCRIPCION_ACTIVO) FROM ACTIVO WHERE ID_ACTIVO = @IN_ID_ACTIVO; 

	-- Crear asiento contable
	INSERT INTO ASIENTO (ID_CLASE, FECHA, DESCRIPCION) VALUES (@IN_ID_NUEVA_CLASE,GETDATE(),@VAR_JE_DESCRIPTION); 
	SET @VAR_ID_ASIENTO = @@IDENTITY; 

	-- Crear cuerpo del asiento
	INSERT INTO ASIENTO_LINEA(ID_ASIENTO,ID_CUENTA_CONTABLE,DESCRIPCION_LINEA,DEBITO,CREDITO) VALUES
		(@VAR_ID_ASIENTO,@VAR_CUENTA_ACTIVO,(SELECT CONCAT('Reclasificación clase ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID),0,@VAR_MONTO_RECONOCIMIENTO),
		(@VAR_ID_ASIENTO,@VAR_CUENTA_ACTIVO_NEW,(SELECT CONCAT('Reclasificación clase ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @IN_ID_NUEVA_CLASE),@VAR_MONTO_RECONOCIMIENTO,0)

	-- Actualizar los balances de las cuentas
	-- Cuenta Debito
	UPDATE CUENTA_CONTABLE SET TOTAL_DEBITOS = TOTAL_DEBITOS + @VAR_MONTO_RECONOCIMIENTO WHERE ID_CUENTA = @VAR_CUENTA_ACTIVO_NEW;
	UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_ACTIVO_NEW;

	--Cuenta credito
	UPDATE CUENTA_CONTABLE SET TOTAL_CREDITOS =  TOTAL_CREDITOS + @VAR_MONTO_RECONOCIMIENTO WHERE ID_CUENTA = @VAR_CUENTA_ACTIVO; 
	UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_ACTIVO; 

	--if the asset has depreciation needs to be updated
	IF @VAR_MONTO_DEPRECIACION > 0
		BEGIN

			--Crear cuerpo ajuste depreciacion
			INSERT INTO ASIENTO_LINEA(ID_ASIENTO,ID_CUENTA_CONTABLE,DESCRIPCION_LINEA,DEBITO,CREDITO) VALUES
				(@VAR_ID_ASIENTO,@VAR_CUENTA_DEPRECIACION,(SELECT CONCAT('Reclasificación dep ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID),@VAR_MONTO_DEPRECIACION,0),
				(@VAR_ID_ASIENTO,@VAR_CUENTA_GASTO,(SELECT CONCAT('Reclasificación gasto dep ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @VAR_CLASE_ACTUAL_ID),0,@VAR_MONTO_DEPRECIACION),
				(@VAR_ID_ASIENTO,@VAR_CUENTA_DEPRECIACION_NEW,(SELECT CONCAT('Reclasificación dep ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @IN_ID_NUEVA_CLASE),0,@VAR_MONTO_DEPRECIACION),
				(@VAR_ID_ASIENTO,@VAR_CUENTA_GASTO_NEW,(SELECT CONCAT('Reclasificación gasto dep ',DESCRIPCION_CLASE) FROM CLASE WHERE ID_CLASE = @IN_ID_NUEVA_CLASE),@VAR_MONTO_DEPRECIACION,0);

			--Ajustar balances
			UPDATE CUENTA_CONTABLE SET TOTAL_DEBITOS = TOTAL_DEBITOS + @VAR_MONTO_DEPRECIACION WHERE ID_CUENTA = @VAR_CUENTA_DEPRECIACION;
			UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_DEPRECIACION; 
			UPDATE CUENTA_CONTABLE SET TOTAL_CREDITOS = TOTAL_CREDITOS + @VAR_MONTO_DEPRECIACION WHERE ID_CUENTA = @VAR_CUENTA_GASTO; 
			UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_GASTO; 

			UPDATE CUENTA_CONTABLE SET TOTAL_DEBITOS = TOTAL_DEBITOS + @VAR_MONTO_DEPRECIACION WHERE ID_CUENTA = @VAR_CUENTA_GASTO_NEW;
			UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_GASTO_NEW; 
			UPDATE CUENTA_CONTABLE SET TOTAL_CREDITOS = TOTAL_CREDITOS + @VAR_MONTO_DEPRECIACION WHERE ID_CUENTA = @VAR_CUENTA_DEPRECIACION_NEW; 
			UPDATE CUENTA_CONTABLE SET BALANCE = TOTAL_DEBITOS - TOTAL_CREDITOS WHERE ID_CUENTA = @VAR_CUENTA_DEPRECIACION_NEW; 

		END;
		
	-- Actualizar activo
	UPDATE ACTIVO SET ID_CLASE = @IN_ID_NUEVA_CLASE WHERE ID_ACTIVO = @IN_ID_ACTIVO; 
	DELETE FROM VALIDACION WHERE ID_ACTIVO = @IN_ID_ACTIVO; 
END


EXEC MODIFICAR_CLASE 17,5
GO

SELECT * FROM ACTIVO WHERE ID_CLASE = 3
SELECT * FROM ACTIVO WHERE ID_CLASE = 5
SELECT * FROM CLASE; 
SELECT * FROM CUENTA_CONTABLE WHERE ID_CATEGORIA = 6
SELECT * FROM AUXILIAR_DEPRECIACION WHERE ID_CLASE = 5 ORDER BY DEPRECIACION_ACUMULADA; 
SELECT * FROM ASIENTO_LINEA WHERE ID_CUENTA_CONTABLE = '6-2-3-167405' ORDER BY CREDITO; 