CREATE OR ALTER VIEW CONCILIACION_BALANCE_CLASE AS
	SELECT 
		*,
		RESULT.BALANCE - RESULT.VALOR_AUXILIAR AS DIFERENCIA
	FROM
		(SELECT
			CC.ID_CLASE,
			CC.ID_CUENTA,
		
			CASE WHEN CC.ID_CATEGORIA_CUENTA = 1 THEN
				(C.DESCRIPCION_CLASE)
			WHEN CC.ID_CATEGORIA_CUENTA = 6 THEN 
				(CONCAT('Dep Acum ',C.DESCRIPCION_CLASE))
			END AS CATEGORIA_CUENTA,

			C.DESCRIPCION_CLASE,
			CCON.BALANCE,

			CASE WHEN CC.ID_CATEGORIA_CUENTA = 1 THEN
				(SELECT SUM(VALOR_ADQUISICION) FROM AUXILIAR_DEPRECIACION WHERE ID_CLASE = CC.ID_CLASE) 
			WHEN CC.ID_CATEGORIA_CUENTA = 6 THEN
				-(SELECT SUM(DEPRECIACION_ACUMULADA) FROM AUXILIAR_DEPRECIACION WHERE ID_CLASE = CC.ID_CLASE)
			END AS VALOR_AUXILIAR
		FROM CLASE_CUENTA CC
		INNER JOIN CLASE C ON C.ID_CLASE = CC.ID_CLASE
		INNER JOIN CUENTA_CONTABLE CCON ON CCON.ID_CUENTA = CC.ID_CUENTA
		WHERE CC.ID_CATEGORIA_CUENTA = 6 OR CC.ID_CATEGORIA_CUENTA = 1) AS RESULT
GO

SELECT * FROM CONCILIACION_BALANCE_CLASE
GO
