USE ASSET_MANAGEMENT;

DROP VIEW VALIDACION_RIESGO_ACTIVOS; 
GO

CREATE VIEW VALIDACION_RIESGO_ACTIVOS AS
	SELECT 
		ID_ACTIVO, 
		ID_DUENNO, 
		DESCRIPCION_ACTIVO, 
		DESCRIPCION_CLASE, 
		ID_CLASE,
		VALIDATION_PERCENTAJE, 
		CASE 
			WHEN (A.VALIDATION_PERCENTAJE < 0.5) THEN 'H' 
			WHEN (A.VALIDATION_PERCENTAJE > 0.5 AND A.VALIDATION_PERCENTAJE < 0.8) THEN 'M' 
			ELSE 'L' END AS VALIDACION_RIESGO
	FROM            
		(SELECT
			A.ID_ACTIVO,
			A.ID_CLASE,
			A.ID_DUENNO,
			A.DESCRIPCION_ACTIVO,
			C.DESCRIPCION_CLASE,
			CAST(ROUND(
				(CAST((SELECT COUNT(*) FROM VALIDACION V WHERE V.ID_ACTIVO = A.ID_ACTIVO) AS DECIMAL(7,5)) / CAST((SELECT COUNT(*) FROM TIPO_VALIDACION AS TP WHERE TP.ID_CLASE = A.ID_CLASE) AS DECIMAL(7,2)) *100)
				,2
			) AS INT) AS VALIDATION_PERCENTAJE
		FROM ACTIVO A
		INNER JOIN CLASE C ON C.ID_CLASE = A.ID_CLASE) AS A
GO

SELECT * FROM VALIDACION_RIESGO_ACTIVOS;

SELECT * FROM ACTIVO WHERE ID_ACTIVO = 4
SELECT COUNT(*) FROM VALIDACION AS V WHERE ID_ACTIVO = 4;
SELECT COUNT(*) FROM TIPO_VALIDACION AS TP WHERE ID_CLASE = 1;

SELECT
	A.ID_ACTIVO,
	A.ID_CLASE,
	A.ID_DUENNO,
	A.DESCRIPCION_ACTIVO,
	C.DESCRIPCION_CLASE,
	ROUND(
		(CAST((SELECT COUNT(*) FROM VALIDACION V WHERE V.ID_ACTIVO = A.ID_ACTIVO) AS DECIMAL(7,5)) / CAST((SELECT COUNT(*) FROM TIPO_VALIDACION AS TP WHERE TP.ID_CLASE = A.ID_CLASE) AS DECIMAL(7,2)) *100)
		,2
	) AS VALIDATION_PERCENTAJE
FROM ACTIVO A
INNER JOIN CLASE C ON C.ID_CLASE = A.ID_CLASE

SELECT TRY_PARSE('5' AS decimal(7,2) using 'en-GB')

SELECT ROUND(CAST(5 AS DECIMAL(7,2)) / CAST(6 AS DECIMAL(7,2)),0)*100
GO

------------------------------------------------------------------------------------------------------------------------------
													-- Chart by risk --
------------------------------------------------------------------------------------------------------------------------------

CREATE VIEW VALIDACION_RIESGO_CLASE AS
	SELECT 
		ID_CLASE,
		DESCRIPCION_CLASE,
		VALIDACION_RIESGO,
		COUNT(*) AS TOTAL_ACTIVOS
	FROM VALIDACION_RIESGO_ACTIVOS
	GROUP BY ID_CLASE,DESCRIPCION_CLASE,VALIDACION_RIESGO;
GO

SELECT * FROM VALIDACION_RIESGO_CLASE; 